"""what Turos own reservation detail says

Revision ID: 092d62f20c14
Revises: d0ce56b5a44c
Create Date: 2026-10-05 18:44:31.468320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092d62f20c14'
down_revision: Union[str, Sequence[str], None] = 'd0ce56b5a44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trip', sa.Column('can_file_reimbursement', sa.Boolean(), nullable=True))
    op.add_column('trip', sa.Column('detail_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'detail_synced_at')
    op.drop_column('trip', 'can_file_reimbursement')
    op.drop_column('trip', 'grace_period_ends_at')
    # ### end Alembic commands ###
