"""when a crossing was asked for

Revision ID: 1f319c265255
Revises: 092d62f20c14
Create Date: 2026-10-05 20:44:05.080513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f319c265255'
down_revision: Union[str, Sequence[str], None] = '092d62f20c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toll', sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toll', 'filed_at')
    # ### end Alembic commands ###
