"""record whether a guess came from memory

Revision ID: 5125b95961e7
Revises: 85ae6b5323c1
Create Date: 2026-09-18 10:25:24.108809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5125b95961e7'
down_revision: Union[str, Sequence[str], None] = '85ae6b5323c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_session', sa.Column(
            'guess_from_memory', sa.Boolean(), nullable=False,
            # A Python-side default does not exist for rows already in the
            # table, so a NOT NULL column added later needs a server default
            # or the migration fails against any non-empty database.
            server_default=sa.false(),
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_session', 'guess_from_memory')
    # ### end Alembic commands ###
