"""segment geometry accepts points

Revision ID: 54def1e0905c
Revises: c1ce74867d5a
Create Date: 2026-09-17 13:05:13.005793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '54def1e0905c'
down_revision: Union[str, Sequence[str], None] = 'c1ce74867d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('street_segment_side', 'geom',
               existing_type=geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Widening LINESTRING to GEOMETRY let point-only block-sides be stored, so
    # narrowing it back fails on any row holding one. The geometry for those is
    # discarded rather than blocking the rollback: reverting this column cannot
    # preserve data the old type could not represent, and a migration that
    # cannot be rolled back against real data is worse than one that says what
    # it loses. CI would not catch this — its database is empty.
    op.execute(
        "UPDATE street_segment_side SET geom = NULL "
        "WHERE geom IS NOT NULL AND ST_GeometryType(geom::geometry) <> 'ST_LineString'"
    )

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('street_segment_side', 'geom',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
