"""a listing id belongs to one vehicle

Revision ID: 73641d7953d8
Revises: 3d678099908a
Create Date: 2026-10-04 18:27:29.014294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73641d7953d8'
down_revision: Union[str, Sequence[str], None] = '3d678099908a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vehicle_turo_listing_id'), 'vehicle', ['turo_listing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_turo_listing_id'), table_name='vehicle')
    # ### end Alembic commands ###
