"""drop the invented guess confidence

Revision ID: 7fe2f16a146e
Revises: 5125b95961e7
Create Date: 2026-09-18 10:34:41.357304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7fe2f16a146e'
down_revision: Union[str, Sequence[str], None] = '5125b95961e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_session', 'guess_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_session', sa.Column('guess_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
