"""telemetry records engine state

Revision ID: 85ae6b5323c1
Revises: 54def1e0905c
Create Date: 2026-09-18 10:14:39.538344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '85ae6b5323c1'
down_revision: Union[str, Sequence[str], None] = '54def1e0905c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_event', sa.Column('is_running', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_event', 'is_running')
    # ### end Alembic commands ###
