"""tolls, and the tag that says whose they are

Revision ID: afb80e0a37a6
Revises: cea5f4a0cf00
Create Date: 2026-10-04 23:15:50.943015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb80e0a37a6'
down_revision: Union[str, Sequence[str], None] = 'cea5f4a0cf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toll',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plaza', sa.String(length=60), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('transponder_id', sa.String(length=40), nullable=True),
    sa.Column('license_plate', sa.String(length=16), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_toll_license_plate'), 'toll', ['license_plate'], unique=False)
    op.create_index(op.f('ix_toll_occurred_at'), 'toll', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_toll_transponder_id'), 'toll', ['transponder_id'], unique=False)
    op.create_index('ix_toll_unrecovered', 'toll', ['recovered_at', 'occurred_at'], unique=False)
    op.add_column('vehicle', sa.Column('ezpass_tag', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_vehicle_ezpass_tag'), 'vehicle', ['ezpass_tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_ezpass_tag'), table_name='vehicle')
    op.drop_column('vehicle', 'ezpass_tag')
    op.drop_index('ix_toll_unrecovered', table_name='toll')
    op.drop_index(op.f('ix_toll_transponder_id'), table_name='toll')
    op.drop_index(op.f('ix_toll_occurred_at'), table_name='toll')
    op.drop_index(op.f('ix_toll_license_plate'), table_name='toll')
    op.drop_table('toll')
    # ### end Alembic commands ###
