"""reimbursement invoices, so the page does not ask twice

Revision ID: c2355eb704b2
Revises: afb80e0a37a6
Create Date: 2026-10-05 14:14:45.000961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2355eb704b2'
down_revision: Union[str, Sequence[str], None] = 'afb80e0a37a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimbursement_invoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('reservation_id', sa.String(length=40), nullable=False),
    sa.Column('turo_invoice_id', sa.String(length=80), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_reimbursement_invoice_reservation_id'), 'reimbursement_invoice', ['reservation_id'], unique=False)
    op.create_index('ix_reimbursement_trip', 'reimbursement_invoice', ['trip_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reimbursement_trip', table_name='reimbursement_invoice')
    op.drop_index(op.f('ix_reimbursement_invoice_reservation_id'), table_name='reimbursement_invoice')
    op.drop_table('reimbursement_invoice')
    # ### end Alembic commands ###
