"""initial schema

Revision ID: cb849f54bac5
Revises: 
Create Date: 2026-09-17 00:52:51.054642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb849f54bac5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('asp_suspension',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suspended_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asp_suspension_suspended_on'), 'asp_suspension', ['suspended_on'], unique=True)
    op.create_table('street_segment_side',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('street_name', sa.String(length=120), nullable=False),
    sa.Column('from_cross_street', sa.String(length=120), nullable=True),
    sa.Column('to_cross_street', sa.String(length=120), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('north', 'south', 'east', 'west', name='street_side'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('fits_van', sa.Boolean(), nullable=True),
    sa.Column('nyc_physical_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_name', 'from_cross_street', 'to_cross_street', 'borough', 'side', name='uq_segment_side')
    )
    op.create_index('ix_segment_geom', 'street_segment_side', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_street_segment_side_nyc_physical_id'), 'street_segment_side', ['nyc_physical_id'], unique=False)
    op.create_index(op.f('ix_street_segment_side_street_name'), 'street_segment_side', ['street_name'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('bouncie_imei', sa.String(length=32), nullable=True),
    sa.Column('turo_listing_id', sa.String(length=40), nullable=True),
    sa.Column('bouncie_nickname', sa.String(length=60), nullable=True),
    sa.Column('tank_gallons', sa.Float(), nullable=True),
    sa.Column('reports_fuel_level', sa.Boolean(), nullable=True),
    sa.Column('reports_obd_odometer', sa.Boolean(), nullable=True),
    sa.Column('needs_large_spot', sa.Boolean(), nullable=False),
    sa.Column('registration_expires', sa.Date(), nullable=True),
    sa.Column('inspection_expires', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicle_bouncie_imei'), 'vehicle', ['bouncie_imei'], unique=True)
    op.create_index(op.f('ix_vehicle_plate'), 'vehicle', ['plate'], unique=True)
    op.create_table('asp_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_side_id', sa.Uuid(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('source', sa.Enum('nyc_signs', 'captured', 'manual', name='rule_source'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_sign_text', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('coalesce(array_length(days_of_week, 1), 0) > 0', name='ck_asp_days_present'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_asp_confidence'),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['segment_side_id'], ['street_segment_side.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asp_rule_segment', 'asp_rule', ['segment_side_id'], unique=False)
    op.create_table('parking_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('segment_side_id', sa.Uuid(), nullable=True),
    sa.Column('guessed_segment_side_id', sa.Uuid(), nullable=True),
    sa.Column('guess_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_id', sa.Uuid(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('must_move_by', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['guessed_segment_side_id'], ['street_segment_side.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_side_id'], ['street_segment_side.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parking_location', 'parking_session', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_parking_session_must_move_by'), 'parking_session', ['must_move_by'], unique=False)
    op.create_index(op.f('ix_parking_session_started_at'), 'parking_session', ['started_at'], unique=False)
    op.create_index('ix_parking_vehicle_active', 'parking_session', ['vehicle_id', 'ended_at'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('asp_move', 'turnaround', 'trip_start', 'trip_end', 'message', 'maintenance', 'fuel', name='task_kind'), nullable=False),
    sa.Column('state', sa.Enum('open', 'done', 'suppressed', 'cancelled', name='task_state'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('due_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('location_label', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('suppressed_reason', sa.String(length=200), nullable=True),
    sa.Column('source_kind', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_kind', 'source_id', 'kind', name='uq_task_source')
    )
    op.create_index(op.f('ix_task_due_by'), 'task', ['due_by'], unique=False)
    op.create_index('ix_task_location', 'task', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_task_open_due', 'task', ['state', 'due_by'], unique=False)
    op.create_index(op.f('ix_task_state'), 'task', ['state'], unique=False)
    op.create_table('telemetry_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('fuel_percent', sa.Float(), nullable=True),
    sa.Column('odometer_miles', sa.Float(), nullable=True),
    sa.Column('battery_status', sa.String(length=30), nullable=True),
    sa.Column('mil_on', sa.Boolean(), nullable=True),
    sa.Column('dtc_count', sa.SmallInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'provider_event_id', name='uq_telemetry_provider_event')
    )
    op.create_index(op.f('ix_telemetry_event_occurred_at'), 'telemetry_event', ['occurred_at'], unique=False)
    op.create_index('ix_telemetry_location', 'telemetry_event', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_telemetry_vehicle_time', 'telemetry_event', ['vehicle_id', 'occurred_at'], unique=False)
    op.create_table('trip',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('turo_trip_id', sa.String(length=40), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('upcoming', 'active', 'completed', 'cancelled', name='trip_state'), nullable=False),
    sa.Column('source', sa.Enum('extension', 'email', 'manual', name='trip_source'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earnings_cents', sa.Integer(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='ck_trip_interval'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_ends_at'), 'trip', ['ends_at'], unique=False)
    op.create_index(op.f('ix_trip_starts_at'), 'trip', ['starts_at'], unique=False)
    op.create_index(op.f('ix_trip_turo_trip_id'), 'trip', ['turo_trip_id'], unique=True)
    op.create_index('ix_trip_vehicle_window', 'trip', ['vehicle_id', 'starts_at', 'ends_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_vehicle_window', table_name='trip')
    op.drop_index(op.f('ix_trip_turo_trip_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_starts_at'), table_name='trip')
    op.drop_index(op.f('ix_trip_ends_at'), table_name='trip')
    op.drop_table('trip')
    op.drop_index('ix_telemetry_vehicle_time', table_name='telemetry_event')
    op.drop_index('ix_telemetry_location', table_name='telemetry_event', postgresql_using='gist')
    op.drop_index(op.f('ix_telemetry_event_occurred_at'), table_name='telemetry_event')
    op.drop_table('telemetry_event')
    op.drop_index(op.f('ix_task_state'), table_name='task')
    op.drop_index('ix_task_open_due', table_name='task')
    op.drop_index('ix_task_location', table_name='task', postgresql_using='gist')
    op.drop_index(op.f('ix_task_due_by'), table_name='task')
    op.drop_table('task')
    op.drop_index('ix_parking_vehicle_active', table_name='parking_session')
    op.drop_index(op.f('ix_parking_session_started_at'), table_name='parking_session')
    op.drop_index(op.f('ix_parking_session_must_move_by'), table_name='parking_session')
    op.drop_index('ix_parking_location', table_name='parking_session', postgresql_using='gist')
    op.drop_table('parking_session')
    op.drop_index('ix_asp_rule_segment', table_name='asp_rule')
    op.drop_table('asp_rule')
    op.drop_index(op.f('ix_vehicle_plate'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_bouncie_imei'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_street_segment_side_street_name'), table_name='street_segment_side')
    op.drop_index(op.f('ix_street_segment_side_nyc_physical_id'), table_name='street_segment_side')
    op.drop_index('ix_segment_geom', table_name='street_segment_side', postgresql_using='gist')
    op.drop_table('street_segment_side')
    op.drop_index(op.f('ix_asp_suspension_suspended_on'), table_name='asp_suspension')
    op.drop_table('asp_suspension')
    op.drop_table('app_user')
    # Alembic's autogenerated downgrade drops the tables but leaves the enum
    # types behind, so a re-upgrade fails with DuplicateObject. Drop them too,
    # or `downgrade base` followed by `upgrade head` cannot round-trip.
    for enum_name in (
        "task_kind", "task_state", "trip_state", "trip_source",
        "rule_source", "street_side",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # ### end Alembic commands ###
