"""keep what the guest actually wrote

Revision ID: cea5f4a0cf00
Revises: 73641d7953d8
Create Date: 2026-10-04 20:56:17.511625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea5f4a0cf00'
down_revision: Union[str, Sequence[str], None] = '73641d7953d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index(op.f('ix_guest_message_received_at'), 'guest_message', ['received_at'], unique=False)
    op.create_index('ix_guest_message_vehicle_time', 'guest_message', ['vehicle_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guest_message_vehicle_time', table_name='guest_message')
    op.drop_index(op.f('ix_guest_message_received_at'), table_name='guest_message')
    op.drop_table('guest_message')
    # ### end Alembic commands ###
