"""what the invoice charged for tolls, line by line

Revision ID: d0ce56b5a44c
Revises: c2355eb704b2
Create Date: 2026-10-05 15:25:41.007755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ce56b5a44c'
down_revision: Union[str, Sequence[str], None] = 'c2355eb704b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, because the table already has rows in production: a
    # NOT NULL column added without one fails the deploy outright. The default
    # is dropped afterwards so new rows go through the model's own default
    # rather than the database's.
    op.add_column(
        'reimbursement_invoice',
        sa.Column(
            'lines',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column('reimbursement_invoice', 'lines', server_default=None)
    op.add_column('reimbursement_invoice', sa.Column('toll_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reimbursement_invoice', 'toll_cents')
    op.drop_column('reimbursement_invoice', 'lines')
    # ### end Alembic commands ###
